name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:   # ✅ 支持手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: 0x1846                  # 固定用户名
      IMAGE_NAME: myapp                        # 镜像名（可改）
      DOCKERFILE_PATH: ./Dockerfile            # Dockerfile 路径（可改）

    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v3

      # 登录 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: 0x1846
          password: dckr_pat_FvZMUrS2ZN8mYxAFtRD92gVIRYo

      # 构建并推送镜像
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ github.ref_type == 'tag' && format('{0}/{1}:{2}', env.DOCKER_USERNAME, env.IMAGE_NAME, github.ref_name) || '' }}
